stages:
  toxvald:
    cmd: Rscript src/1_integrate_toxvaldb.py
    deps: 
      - src/1_integrate_toxvaldb.py
    outs:
      - cache/toxvaldb
  chembl:
    cmd: Rscript src/2_integrate_chembl.R
    deps: 
      - src/2_integrate_chembl.R
    outs:
      - cache/toxvaldb
