stages:
  toxvaldb:
    cmd: Rscript src/1_integrate_toxvaldb.R
    deps: 
      - src/1_integrate_toxvaldb.R
    outs:
      - brick/toxvaldb
  chembl:
    cmd: Rscript src/2_integrate_chembl.R
    deps: 
      - src/2_integrate_chembl.R
    outs:
      - brick/chembl
  tox21:
    cmd: Rscript src/3_integrate_tox21.R
    deps: 
      - src/3_integrate_tox21.R
    outs:
      - brick/tox21
  harmonization:
    cmd: Rscript src/4_harmonization.R
    deps: 
      - brick/toxvaldb
      - brick/chembl
      - brick/tox21
    outs:
      - brick/harmonized